---
name: "SerializdSync"
guid: "6616e553-2549-4e36-abe2-0678676fd506"
version: "1.0.0.0"
targetAbi: "12.0.0.0"
framework: "net10.0"
overview: "Short description about your plugin"
description: >
  This is a longer description that can span more than one
  line and include details about your plugin.
category: "General"
owner: "jellyfin"
artifacts:
- "Jellyfin.Plugin.SerializdSync.dll"
changelog: >
  changelog
